// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isjustbgjteeqzidnrhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzanVzdGJnanRlZXF6aWRucmhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3ODMwMjgsImV4cCI6MjA2NDM1OTAyOH0.FNOAJygMc4kPRfm7poeeDTMwN_s4VWGcjPVvYjxUg5E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);